version: '3.6'

services:
  ##
  ## The Compositor
  ##

  compositor:
    image: mathhub/compositor:${COMPOSITOR_VERSION}
    container_name: mh_compositor_${MATHHUB_UUID}
    labels:
      - com.centurylinklabs.watchtower.enable=${AUTO_UPDATE_OTHER}
    ports:
      - target: 80
        published: ${MATHHUB_PORT}
    
    networks:
      mhinternal:
        aliases:
          - compositor
        
    depends_on:
      - frontend
      - admin
      - portainer
      - news
      - config
      - mmt
    
    restart: always
  ##
  ## WATCHTOWER
  ##
  watchtower:
      image: v2tec/watchtower:${WATCHTOWER_VERSION}
      container_name: mh_watchtower_${MATHHUB_UUID}
      labels:
      - com.centurylinklabs.watchtower.enable=${AUTO_UPDATE_OTHER}
    
      command: --label-enable --cleanup mh_nginx_${MATHHUB_UUID} mh_compositor_${MATHHUB_UUID} mh_watchtower_${MATHHUB_UUID} mh_frontend_${MATHHUB_UUID} mh_letitgo_${MATHHUB_UUID} mh_news_${MATHHUB_UUID} mh_admin_${MATHHUB_UUID} mh_portainer_${MATHHUB_UUID} mh_mmt_${MATHHUB_UUID}

      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock:ro"
      
      networks:
        mhinternal:
          aliases:
            - watchtower
    
      restart: always
  ##
  ## The Frontend
  ##
  frontend:
    image: mathhub/frontend:${FRONTEND_VERSION}
    container_name: mh_frontend_${MATHHUB_UUID}
    labels:
      - com.centurylinklabs.watchtower.enable=${AUTO_UPDATE_OTHER}
    
    networks:
      mhinternal:
        aliases:
          - watchtower
    
    restart: always
  
  ##
  ## The Config
  ##
  config:
    image: mathhub/letitgo:${LETITGO_VERSION}
    container_name: mh_letitgo_${MATHHUB_UUID}
    env_file:
      - .config/letitgo
    labels:
      - com.centurylinklabs.watchtower.enable=${AUTO_UPDATE_OTHER}
    
    command: 'SHOW_RIBBON'
    
    networks:
      mhinternal:
        aliases:
          - config
    
    restart: always
  
  ##
  ## The News
  ##
  news:
    image: mathhub/news:${NEWS_VERSION}
    container_name: mh_news_${MATHHUB_UUID}
    labels:
      - com.centurylinklabs.watchtower.enable=${AUTO_UPDATE_NEWS}
    
    networks:
      mhinternal:
        aliases:
          - news
    
    restart: always
  
  ##
  ## The Admin Interface
  ##
  admin:
    image: mathhub/admin:${ADMIN_VERSION}
    container_name: mh_admin_${MATHHUB_UUID}
    env_file:
      - .config/admin
    environment:
      - DJANGO_ALLOWED_HOSTS=*
    labels:
      - com.centurylinklabs.watchtower.enable=${AUTO_UPDATE_OTHER}
    
    volumes:
      - "admin:/data/"

    networks:
      mhinternal:
        aliases:
          - admin
    
    restart: always
  
  ##
  ## Portainer
  ##
  portainer:
    image: portainer/portainer:${PORTAINER_VERSION}
    container_name: mh_portainer_${MATHHUB_UUID}
    labels:
      - com.centurylinklabs.watchtower.enable=${AUTO_UPDATE_OTHER}
    
    command: "--no-auth -H unix:///var/run/docker.sock"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "portainer:/data/"
    
    networks:
      mhinternal:
        aliases:
          - portainer
    
    restart: always
  
  ##
  ## MMT
  ##
  mmt:
    image: kwarc/mmt:${MMT_VERSION}
    container_name: mh_mmt_${MATHHUB_UUID}
    env_file:
      - .config/mmt
    labels:
      - com.centurylinklabs.watchtower.enable=${AUTO_UPDATE_OTHER}

    command: "-w --file /content/MathHub/meta/inf/mathhub.msl"

    environment:
      MMT_ARCHIVES: meta/inf HelloWorld/* smglom/* MMT/LFX MMT/urtheories MMT/examples MitM/meta-inf MitM/Foundation MitM/smglom MitM/models ODK/meta-inf ODK/lmfdb ODK/GAP ODK/Sage ODK/Sage ODK/Singular ODK/knowls ODK/math ODK/Demos Isabelle/* Tutorials/Mathematicians

    volumes:
      - mmt:/content/
    
    networks:
      mhinternal:
        aliases:
          - mmt
    
    restart: always
  
networks:
  mhinternal:

volumes:
  mmt:
  admin:
  portainer:
  nginx_vhost:
  nginx_certs:
  nginx_html:
  nginx_dhparam:
