version: '3.6'

services:
  ##
  ## Nginx entry point
  ##
  nginx:
    image: jwilder/nginx-proxy:${NGINX_PROXY_VERSION}
    env_file:
      - .config/nginx
    
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true
      - com.centurylinklabs.watchtower.enable=${AUTO_UPDATE_OTHER}
      
    
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "nginx_dhparam:/etc/nginx/dhparam"
      - "nginx_html:/usr/share/nginx/html"
      - "nginx_vhost:/etc/nginx/vhost.d"
      - "nginx_certs:/etc/nginx/certs"
       
    depends_on:
    - compositor
    
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mhinternal
      - default
  
  ##
  ## Letsencrypt-Companion
  ##
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:${PROXY_COMPANION_VERSION}
    labels:
      - com.centurylinklabs.watchtower.enable=${AUTO_UPDATE_OTHER}
    
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "nginx_dhparam:/etc/nginx/dhparam"
      - "nginx_html:/usr/share/nginx/html"
      - "nginx_vhost:/etc/nginx/vhost.d"
      - "nginx_certs:/etc/nginx/certs"

    depends_on:
      - nginx
    
    networks:
      - mhinternal

  ##
  ## The Compositor
  ##

  compositor:
    image: mathhub/compositor:${COMPOSITOR_VERSION}
    env_file:
      - .config/compositor
    environment:
      - VIRTUAL_PORT=80
    labels:
      - com.centurylinklabs.watchtower.enable=${AUTO_UPDATE_OTHER}
    
    networks:
      - mhinternal
    
    depends_on:
      - frontend
      - admin
      - portainer
      - news
      - config
      - mmt
  ##
  ## WATCHTOWER
  ##
  watchtower:
      image: v2tec/watchtower:${WATCHTOWER_VERSION}
      labels:
      - com.centurylinklabs.watchtower.enable=${AUTO_UPDATE_OTHER}
    
      command: --label-enable --cleanup

      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock:ro"
      
      networks:
        - mhinternal
  ##
  ## The Frontend
  ##
  frontend:
    image: mathhub/frontend:${FRONTEND_VERSION}
    labels:
      - com.centurylinklabs.watchtower.enable=${AUTO_UPDATE_OTHER}
    
    networks:
      - mhinternal
  
  ##
  ## The Config
  ##
  config:
    image: mathhub/letitgo:${LETITGO_VERSION}
    env_file:
      - .config/letitgo
    labels:
      - com.centurylinklabs.watchtower.enable=${AUTO_UPDATE_OTHER}
    
    command: 'SHOW_RIBBON'
    
    networks:
      - mhinternal
  
  ##
  ## The News
  ##
  news:
    image: mathhub/news:${NEWS_VERSION}
    labels:
      - com.centurylinklabs.watchtower.enable=${AUTO_UPDATE_NEWS}
    
    networks:
      - mhinternal
  
  ##
  ## The Admin Interface
  ##
  admin:
    image: mathhub/admin:${ADMIN_VERSION}
    env_file:
      - .config/admin
    environment:
      - DJANGO_ALLOWED_HOSTS=*
    labels:
      - com.centurylinklabs.watchtower.enable=${AUTO_UPDATE_OTHER}
    
    volumes:
      - "admin:/data/"

    networks:
      - mhinternal
  
  ##
  ## Portainer
  ##
  portainer:
    image: portainer/portainer:${PORTAINER_VERSION}
    labels:
      - com.centurylinklabs.watchtower.enable=${AUTO_UPDATE_OTHER}
    
    command: "--no-auth -H unix:///var/run/docker.sock"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "portainer:/data/"
    
    networks:
      - mhinternal
  
  ##
  ## MMT
  ##
  mmt:
    image: kwarc/mmt:${MMT_VERSION}
    env_file:
      - .config/mmt
    labels:
      - com.centurylinklabs.watchtower.enable=${AUTO_UPDATE_OTHER}

    command: "-w --file /content/MathHub/meta/inf/mathhub.msl"

    environment:
      MMT_ARCHIVES: meta/inf HelloWorld/* smglom/* MMT/LFX MMT/urtheories MMT/examples MitM/meta-inf MitM/Foundation MitM/smglom MitM/models ODK/meta-inf ODK/lmfdb ODK/GAP ODK/Sage ODK/Sage ODK/Singular ODK/knowls ODK/math ODK/Demos Isabelle/*

    volumes:
      - mmt:/content/
    
    networks:
      - mhinternal
  
networks:
  mhinternal:

volumes:
  mmt:
  admin:
  portainer:
  nginx_vhost:
  nginx_certs:
  nginx_html:
  nginx_dhparam:
